### ISSUE TITLE
[Enhancement] Vertical US ID Support

### ISSUE THREAD

**Issue by ajboxjr** [BlinkID/blinkid-react-native#105]
Many ID's under the age of 21 come shaped vertically. It would be really great if there was compatibility for these cards.

**Comment by eddieMicroblink** [comment]
Hello @ajboxjr 

Since v5 of our BlinkID SDK we support scanning vertical documents,
however, as of right now you can only extract the Face Image from the front side.
We hope this helps and we will keep you updated on any changes and improvements

Regards,
Edhem

**Comment by mparadina** [comment]
Hi @ajboxjr 

As this issue is inactive we would like to solve it. 
In case this is still an active issue for you, feel free to re-open it or create a new issue.

Also, you can always contact us directly at support@microblink.com for further questions.
We will be more than glad to help.

Regards,
Milan
