### ISSUE TITLE
The Camera permission denied screen has some style issues

### ISSUE THREAD

**Issue by keshk26** [BlinkID/blinkid-react-native#206]
Hello,

These are the package versions I am using.

"blinkid-react-native": "^5.17.0"
 "react-native": "^0.68.2"
 
 I tested this on iOS 16.0.3. iPhone 13.
 
 I noticed that if Camera permission has been denied when I use the BlinkID library, then I see a great permissions screen asking the user to enabled permissions. This is great UX but there are some formatting issues on the screen. I am seeing  **{font@Medium}** and **{/font}** text on the screen. It would great if you could remove this text! See screenshot below.
 
 Thanks,
Keshav
 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/18268072/211660249-8a468900-045d-412e-aa78-88f674df582b.png)

**Comment by MBrizic01** [comment]
Hello @keshk26, thank you for reaching out. 

We were aware of the text style issue and fixed it in the 5.19 release on native iOS. Since the last RN release was 5.17, we had yet to apply the fix. 
Also, we had a major release [v6.0](https://microblink.com/identity-document-scanning-product-updates-november-2022/) coming out the last month on [native](https://github.com/BlinkID/blinkid-ios/blob/master/Release%20notes.md#600) platforms. 
By the end of January, v6.1 will be out on React Native, including all the fixes and new features added to the SDK since 5.17., so you can promptly update. 
Meanwhile, we suggest you fix it manually by going to this path: blinkid-react-native/Sample/ios/Pods/PPBlinkID/Microblink.xcframework/ios-arm64/Microblink.framework/en.strings

I hope this helps!
