### ISSUE TITLE
This license is invalid for version 6.1. It is valid only for licensee 'packageName', for product 'BlinkID' on platform 'Android' up to version 5.27.

### ISSUE THREAD

**Issue by keshk26** [BlinkID/blinkid-react-native#210]
"react-native": "0.70.6"
"blinkid-react-native": "^6.1.0"

Hello, I am trying to upgrade to the latest version of this package (6.1.0) from version (5.17.0). I received an error that license key is invalid for version 6.1 for both iOS and Android. How do we go about fixing this issue? How will this affect users using older version of Microblink? We submitted a support request about this earlier this week (2/27). Please let us know how to resolve this.

Thanks,
Keshav

**Comment by MBrizic01** [comment]
Hello @keshk26 thank you for reaching out. To use version 6.1.0 and forwards, you need a new license, which will include the right to use the latest release. Since our licenses are backward compatible, you can also use them on the older version (5). Please reach out to support@microblink.com and provide us with your current license key number and package name, and we will update the license for you, explain the transition to the new version, and assist with any other inquiries.
