### ISSUE TITLE
Custom layout (Android)

### ISSUE THREAD

**Issue by nazarTrynko** [BlinkID/blinkid-react-native#23]
Hi again! I would also like to add my own layout for camera view in Android. Is it possible?

**Comment by lirfu** [comment]
Hi @nazarTrynko,

**blinkid-react-native** does not support custom layouts since it is only an example wrapper for the BlinkID native SDK for [Android](https://github.com/BlinkID/blinkid-android) and [iOS](https://github.com/BlinkID/blinkid-ios). 
For 100% of features and maximum control consider using native SDK by implementing your own Android wrapper in your project.

You can use [BlinkIDModule.java](https://github.com/BlinkID/blinkid-react-native/blob/master/src/android/src/main/java/com/microblink/reactnative/blinkid/BlinkIDModule.java) as a template for your custom wrapper.

**Comment by nazarTrynko** [comment]
@lirfu thank you, I'll do it that way
