### ISSUE TITLE
"scanningResult.resultList.length" always 1

### ISSUE THREAD

**Issue by matias91** [BlinkID/blinkid-react-native#36]
Hi! Thanks for the great work!

I'm trying to use more than one recognizer to scan the front of argentinian ID's, but the `resultList`  array has always one item, and the `resultType` seems to be different each time.
If i use only one recognizer, the result is the expected.

As a workaround, I use an instance of blinkid with each recognizer i need, but is a poor solution and complicates the user experience.

Maybe I'm doing something wrong, or this is the expected behaviour?

Active Recognizers: **[RECOGNIZER_DOCUMENT_FACE, RECOGNIZER_PDF417]**

**Comment by lirfu** [comment]
Hi @matias91,

this is expected behaviour of this demo wrapper. The wrapper is intended to return only one result, so it is recommended to use recognizers one by one (to prevent results competing), as you implemented.

The only way to slightly improve this is to implement your own wrapper and activity that starts scanning procedures in a row. However you still need to perform two scans in order to get both results.

**Comment by matias91** [comment]
Thanks for the answer, @lirfu!!

I got confused because of the `scanningResult` returns an Array with the `resultType`.
If is going to be always one, needs to be an Array?

**Feel free to close this, my last question is only curiosity.**

Regards!

**Comment by lirfu** [comment]
Hi @matias91,

there is a possibility that the wrapper could return two or more results if more recognizers are specified. That is enabled with a flag [here](https://github.com/BlinkID/blinkid-react-native/blob/master/src/android/src/main/java/com/microblink/reactnative/blinkid/BlinkIDModule.java#L190).

However, there is no guarantee that all the specified recognizers will return their result in the current pass through the recognizers (recognizers are started as a chain in cycles).

That's why it's recommended to use this wrapper with a single recognizer, or implement your own plugin and logic.

Hope this answer helps.
Best regards!
