### ISSUE TITLE
scan US license with EudlRecognizer

### ISSUE THREAD

**Issue by pgmemk** [BlinkID/blinkid-react-native#69]
Just by accident I scanned US license with EudlRecognizer with additional settings for images see the result data below.

The data are bad. The face and fullDocument images are good. 

There is no identificator that the scanned data are not valid.

```
"[
  {
    "resultState": 2,
    "slaveRecognizerResult": {
      "resultState": 2,
      "address": "",
      "birthData": "8..18.8",
      "country": 2,
      "driverNumber": "01032017",
      "expiryDate": {
        "day": 0,
        "month": 0,
        "year": 0
      },
      "faceImage": "...",
      "fullDocumentImage": "..."
      "firstName": "",
      "issueDate": {
        "day": 0,
        "month": 0,
        "year": 0
      },
      "issuingAuthority": "",
      "lastName": "Acs D",
      "personalNumber": ""
    }
  }
]"
```

**Comment by i1E** [comment]
Hi @pgmemk,

sometimes specific recognizer for some document type can read partial data from other document type as it happened in your case. This happens because some fields are placed on the expected positions on the document and they are successfully parsed and results are returned on timeout.

This result is not valid (its state is `RecognizerResultState.uncertain`) and there is property in the returned result object that you can use to check whether result is valid or not. You can see in `BlinkID/recognizer.js` that every recognizer result has property `resultState`.

For example, in your application code for EudlRecognizerResult you can check its state in the following way:

```
...
 } else if (result instanceof BlinkIDReactNative.EudlRecognizerResult) {
    if (result.resultState == RecognizerResultState.valid) {
        // do something with the valid result
    } 
}
...

```
