### ISSUE TITLE
Warning: Module MBMicroblinkModule requires main queue setup since it overrides 'init' but doesn't implement 'requiresMainQueueSetup'

### ISSUE THREAD

**Issue by MarcoLude** [BlinkID/blinkid-react-native#93]
React native 0.57.4
BlinkID 4.3.0
Warning received on App start-up on iOS platform just after package installation and CocoaPods linking:

> Module MBMicroblinkModule requires main queue setup since it overrides 'init' but doesn't implement 'requiresMainQueueSetup'. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

On Android works fine.

Is this something that should be fixed inside the module? Or can I do something to solve this warning?

**Comment by jcular** [comment]
Hi @MarcoLude,

thx for reporting this, we'll look into it.
This should be fixed in the module, 

Kind regards,
Jure

**Comment by mparadina** [comment]
Hello @MarcoLude 

We apologize so the very long delay in answering. 

Since you have submitted this issue, we have made significant improvements regarding the React Native plugin.
If possible, could you please try out the latest version of BlinkID and let us know if this is still an open issue for you?

Also, if you come across any difficulties, you can always contact us directly at support@microblink.com

Once again, apologizes for the delay and regards,
Milan

**Comment by mparadina** [comment]
Hi @MarcoLude 

As this issue is inactive, I am closing it.
However, if this is still an open issue for you, feel free to re-open this one or create a new issue.

Also, you can always contact us directly at support@microblink.com for any additional questions.

Regards,
Milan
